
version: '3'

services:

  frontend_service:
    build: ./frontend_service
    ports:
      - "5000:5000"
    depends_on:
      - catalog_service_1
      - catalog_service_2
      - order_service_1
      - order_service_2

  catalog_service_1:
    build: ./catalog_service
    ports:
      - "5001"
  
  catalog_service_2:
    build: ./catalog_service
    ports:
      - "5002"

  order_service_1:
    build: ./order_service
    ports:
      - "5003"

  order_service_2:
    build: ./order_service
    ports:
      - "5004"
